/**
 * Business Analyst — type definitions.
 *
 * The BA workflow reads a Jira ticket (summary, description, comments, related issues)
 * and classifies the content into five spec-kit-aligned categories.
 */

/* ------------------------------------------------------------------ */
/*  Analysis result                                                    */
/* ------------------------------------------------------------------ */

/**
 * Each field maps 1:1 to a spec-kit step.
 * A field is `null` when the BA could not extract meaningful content for that step.
 */
export interface BaAnalysisResult {
  /** What to build and why — scope, users, use cases, success criteria, constraints. No implementation details. */
  specifyInput: string | null;
  /** Ambiguities, missing requirements, unclear behavior, assumptions, contradictions. Questions, not solutions. */
  clarifyInput: string | null;
  /** Technical / architectural design — system design, tech choices, data models, integrations, NFRs. Not tasks or code. */
  planInput: string | null;
  /** Concrete, ordered, actionable work items. Imperative language. Small, discrete. No code blocks. */
  tasksInput: string | null;
  /** Actual code, snippets, diffs, test code, or concrete file changes. Execution artifacts, not descriptions. */
  implementInput: string | null;
}

/* ------------------------------------------------------------------ */
/*  Outcome                                                            */
/* ------------------------------------------------------------------ */

interface BaOutcomeComplete {
  status: 'complete';
  result: BaAnalysisResult;
}

interface BaOutcomeIncomplete {
  status: 'incomplete';
  /** Markdown-formatted questions to post back to Jira. */
  questions: string;
  /** Partial result — may have some fields populated. */
  partialResult?: Partial<BaAnalysisResult>;
}

export type BaOutcome = BaOutcomeComplete | BaOutcomeIncomplete;

/* ------------------------------------------------------------------ */
/*  Ticket context assembled for the LLM prompt                       */
/* ------------------------------------------------------------------ */

export interface JiraComment {
  author: string;
  body: string;
  created: string;
  /** True when this comment was generated by the Business Analyst automation. */
  isBAGenerated?: boolean;
}

export interface RelatedIssueBrief {
  key: string;
  summary: string;
  status: string;
  type: string;
}

export interface TicketContext {
  issueKey: string;
  summary: string;
  description: string;
  comments: JiraComment[];
  relatedIssues: RelatedIssueBrief[];
}
